#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BasicTable.Resource", IsApplication=true)]

namespace BasicTable
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int back_swipe = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int left_swipe = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int right_swipe = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int blue_event_label = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int date_color = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int separator_background = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int customBorder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_american_football = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_australian_rules = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_bandy = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_baseball = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_basketball = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_beach_soccer = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_boxing = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_chess = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_cricket = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_curling = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_cycling = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_darts = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_daughts = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_floorball = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_gaelic_football = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_golf = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_handball = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_icehockey = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_motor = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_motorbike = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icon_snooker = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icon_soccer = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon_table_tennis = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icon_tennis = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon_trotting = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon_ultimate_fighting = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon_volleyball = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int monthSelectorBorder = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int buttonNextMonth = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int buttonPreviousMonth = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int iconSport = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int layoutMonthEvent = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int linearMonthSelector = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int listItemSection = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int listViewEvents = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int textEventTime = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int textEventTitle = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int textMonth = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int thumbnail = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListEvents_row = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListEventsSeparator = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
